CREATE TABLE IF NOT EXISTS `Commentaries` (
  `id` VARCHAR(36) PRIMARY KEY,
  `userId` VARCHAR(36),
  `taskId` VARCHAR(36),
  `content` TEXT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_comment_user` FOREIGN KEY (`userId`) REFERENCES `Users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_comment_task` FOREIGN KEY (`taskId`) REFERENCES `Tasks`(`id`) ON DELETE CASCADE
);

