CREATE TABLE IF NOT EXISTS `Projects` (
  `id` VARCHAR(36) PRIMARY KEY,
  `name` VARCHAR(150),
  `description` TEXT,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

