CREATE TABLE IF NOT EXISTS `Roles` (
  `id` VARCHAR(36) PRIMARY KEY,
  `userId` VARCHAR(36),
  `teamId` VARCHAR(36),
  `role` ENUM('admin', 'member'),
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_roles_user` FOREIGN KEY (`userId`) REFERENCES `Users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_roles_team` FOREIGN KEY (`teamId`) REFERENCES `Teams`(`id`) ON DELETE CASCADE
);
