CREATE TABLE IF NOT EXISTS `Roles` (
  `id` VARCHAR(36) PRIMARY KEY,
  `name` ENUM('admin', 'member'),
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
