CREATE TABLE IF NOT EXISTS `Teams` (
  `id` VARCHAR(36) PRIMARY KEY,
  `name` VARCHAR(100),
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

