CREATE TABLE IF NOT EXISTS `Users` (
  `id` VARCHAR(36) PRIMARY KEY,
  `name` VARCHAR(100),
  `middleName` VARCHAR(100),
  `lastName` VARCHAR(100),
  `secondLastName` VARCHAR(100),
  `email` VARCHAR(255) UNIQUE,
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

