CREATE TABLE IF NOT EXISTS `UserRoles` (
  `id` VARCHAR(36) PRIMARY KEY,
  `userId` VARCHAR(36),
  `roleId` VARCHAR(36),
  `createdAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_userroles_user` FOREIGN KEY (`userId`) REFERENCES `Users`(`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_userroles_role` FOREIGN KEY (`roleId`) REFERENCES `Roles`(`id`) ON DELETE CASCADE
); 